# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-08-17 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_auto_20200817_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='projects',
        ),
        migrations.AddField(
            model_name='profile',
            name='projects',
            field=models.TextField(blank=True),
        ),
    ]
